services:
  - type: web
    name: resumehub-backend
    env: docker
    dockerfilePath: Dockerfile
    dockerContext: .
    plan: free

    envVars:
      - key: DB_URL
        sync: false

      - key: DB_USERNAME
        sync: false

      - key: DB_PASSWORD
        sync: false

      - key: RESEND_API_KEY
        sync: false

      - key: JWT_SECRET
        generateValue: true

      - key: CORS_ALLOWED_ORIGINS
        value: https://resumehub-backend.onrender.com
